[project]
name = "genaii"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cohere>=5.20.5",
    "langchain-cohere>=0.5.0",
    "langchain-community>=0.4.1",
    "langchain-google-genai>=4.2.0",
    "langchain-openai>=1.1.9",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.0",
    "openai>=2.21.0",
    "pypdf>=6.7.0",
    "python-dotenv>=1.2.1",
]
